# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve the matrix equation AX = B for X for an array of matrices A
#'
#' @param a 3D array. For dimensions x,y,z, iteration is over dimension z ("slices")
#' @param b Matrix with dimensions y,x
#' @return Matrix of solutions (x,z)
#' @import Rcpp
solvearray <- function(a, b) {
    .Call('_rrtm_solvearray', PACKAGE = 'rrtm', a, b)
}

